### ISSUE TITLE
In environments with over 1000 content searches, report does not information on DSE workshop searches

### ISSUE THREAD

**Issue by afcepiq** [microsoft/CompliancePartnerWorkshops#16]
Unfortunately, we find that many customers have thousands of content searches going back years. Under these circumstances, the script will not report on recent content searches.  A simple, but brute force, method to deal with this is changing line 232 to:

$search = Get-ComplianceSearch -ResultSize Unlimited | Sort-Object -Property LastModifiedTime -Descending

A better way to deal with it may be to filter the results from Get-ComplianceSearch to searches last modified in the past 90 days - assuming that the script is being run in a timely manner. Of course, this still may take longer than necessary to run and return irrelevant data the customer does not want reported on.

An even better way to address would be instructing partners running the engagements to create a Standard eDiscovery case and have the script return just the searches within the case.  I suggest that partner guidance suggest a standard case name.  The script would look for a case with that name. If case not found, it should prompt for a case name.

**Comment by jimbanach** [comment]
HI,

Thanks for the feedback, we are in the process of testing the updated version, where we are taking the approach of only pulling searches more recently done (as you can't use a server side filter on get-compliance search).  

Thanks for the feedback on the eDiscovery case as well.  With the new portal launch and product changes we are always looking to see if there are easier ways to achieve the desired outcome without adding too many additional steps.
